apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: velocity
  namespace: emortalmc

spec:
  replicas: 1
  scheduling: Packed

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%

  template:
    spec:
      players:
        initialCapacity: 1500

      ports:
        - name: default
          portPolicy: Static
          hostPort: 25565
          containerPort: 25565
          protocol: TCP

      health:
        initialDelaySeconds: 10
        periodSeconds: 6
        failureThreshold: 2

      template:
        spec:
          serviceAccountName: default-gameserver
          automountServiceAccountToken: true
          
          nodeSelector:
            kubernetes.io/hostname: emc-01 # Only deploy 1 velocity on the main node

          volumes:
            - name: gamemodes
              configMap:
                name: gamemodes
          containers:
          
            - name: velocity
              image: ghcr.io/emortalmc/velocity-core:b3f73448d46a8b1345bbf789929ea1d16818a3a3
              args: ["--enable-preview", "-XX:+UseZGC", "-Xmx3G", "-Xms3G", "-jar", "/app/velocity.jar"]

              lifecycle:
                postStart:
                  exec:
                    command: [ "/bin/sh", "-c", "echo $VELOCITY_FORWARDING_SECRET > /app/forwarding.secret" ]

              volumeMounts:
                - name: gamemodes
                  mountPath: /app/config/gamemodes

              env:
                - name: JAVA_OPTS
                  value: "-Xms4G -Xmx4G"
                - name: VELOCITY_FORWARDING_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: velocity-forwarding-token
                      key: forwarding.secret
                      optional: false
                - name: KAFKA_HOST
                  value: default-kafka-bootstrap
                - name: KAFKA_PORT
                  value: "9092"
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: FLEET_NAME
                  value: velocity
                - name: PYROSCOPE_SERVER_ADDRESS
                  valueFrom:
                    configMapKeyRef:
                      name: pyroscope
                      key: address

              resources:
                limits:
                  memory: "8Gi"
                  cpu: "3"
                requests:
                  memory: "8Gi"
                  cpu: "500m"
