name: "Build and deploy"

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "emortalmc/actions/java/build@main"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          java-version: "21"
          java-distribution: "zulu"

  deploy:
    needs: "build"
    runs-on: "ubuntu-latest"
    if: "github.ref == 'refs/heads/main'"
    steps:
      - uses: "emortalmc/actions/argo-sync@main"
        with:
          deployment-name: "velocity"
          values-path: "velocity/values.yaml"
          deployments-repo-token: "${{ secrets.DEPLOYMENTS_REPO_TOKEN }}"
